### ISSUE TITLE
Statement of contributions

### ISSUE THREAD

**Issue by NicoleWij** [NicoleWij/Group_5_Assignment_2#3]
Add statements of contributions for our README.

**Comment by Maja-Larsson** [comment]
My contribution: been active and created code and implementation for feature 1 and 2. Contributed to documentation of README and wrote the documentation for property semat.

**Comment by RiLoGosh** [comment]
Simon's Contributions: Active in general design and implementation for all core features. Primarily involved in the development of core feature 1, designing and writing the code for the cloning and compilation features of the CI. Contributed to general documentation throughout the assignment.
